### PR TITLE
[#168686562] fastruby.io Style Guide: Improve H1, H2, H3 styles to better represent the hierarchy 

### PR DESCRIPTION
**Pull request by nykka**
This PR:

- Adds the H3 styles

image

### CODE REVIEW

**Review by etagwerker — APPROVED** [review]
@nykka Looks good, thanks! 💯

**Comment by etagwerker** [comment]
@nykka Could you resolve the conflicts? Thanks!

**Comment by lubc** [comment]
@nykka reminder about the git conflicts  👀

**Review by etagwerker — CHANGES_REQUESTED** [review]
@nykka Now that the style guide has been gemified, we will need you to resolve the conflicts. Sorry about that. Could you look into it?

**Comment by nykka** [comment]
> @nykka Now that the style guide has been gemified, we will need you to resolve the conflicts. Sorry about that. Could you look into it?

@etagwerker I think this has not use, since the styleguide has changed its structure and the styles were updated.

**Comment by etagwerker** [comment]
@nykka Got it, thanks!

**Pull request closed without merging**
