### PR TITLE
Created styleguide for FastRuby

### PR DESCRIPTION
**Pull request by lubc**

### CODE REVIEW

**Comment by nykka** [comment]
Thanks @lubc

**Review by etagwerker — CHANGES_REQUESTED** [review]
@nykka Hi, thanks for submitting this PR! Could you follow our pull request guidelines? https://github.com/ombulabs/guides/wiki/23.-Submitting-Pull-Requests#write-useful-descriptions

It would make this 10 times easier to review 😄

**Comment by nykka** [comment]
This PR:
- Creates all the styles and elements for the FastRuby style guide

How it will look like with this PR:
Screen Shot 2019-03-13 at 11 17 43
Screen Shot 2019-03-13 at 11 17 51
Screen Shot 2019-03-13 at 11 18 02
Screen Shot 2019-03-13 at 11 18 16

**Review by etagwerker — APPROVED** [review]

**Comment by etagwerker** [comment]
@nykka Great, thanks!

**Pull request merged**
