### PR TITLE
[#168521330] DRY css across all FastRuby sites

### PR DESCRIPTION
**Pull request by nykka**
This PR:

- Updates the old styleguide with the new components and styles for fastruby products.

How it will look after this PR:
screencapture-file-Users-veronica-Sites-fastruby-styleguide-index-html-2019-11-26-13_30_53

### CODE REVIEW

**Review by etagwerker — CHANGES_REQUESTED** [review]
@nykka I think there is a problem here. Where did the content from `<head>` go? 

Screen Shot 2019-12-02 at 3 12 50 PM
Screen Shot 2019-12-02 at 3 13 03 PM

I'm trying to test this locally but I don't see the CSS...

**Comment by nykka** [comment]
@etagwerker You don't have the static folder where the css and js files are compiled. You can run `rake precompile_assets` to generate it. 
This folder is in the `gitignore` file so that is why it was not added to this PR.
Maybe we can stop ignoring it so it would be included in the files.

**Review by etagwerker — CHANGES_REQUESTED** [review]
@nykka Got it. Please remember to include all steps to test when you submit a PR. 

Also, does GitHub Pages have support for running a rake task before deploying changes? Just wondering if this will work seamlessly when we merge it to `gh-pages`. So far it looks like gemifying the style guide broke GitHub Pages: https://fastruby.github.io/styleguide/

Screen Shot 2019-12-02 at 3 50 44 PM

Could you sort out that bug @nykka? /cc @sasha-h-reenhanced 

## Feedback for this PR

Logo in Safari 13 looks weird: 

Screen Shot 2019-12-02 at 3 47 13 PM

Domain should be formatted like this: FastRuby.io: 

Screen Shot 2019-12-02 at 3 47 15 PM

Arrow icon is not showing up in Safari. It seems to work fine in Chrome:

Screen Shot 2019-12-02 at 3 47 18 PM
Screen Shot 2019-12-02 at 3 47 23 PM

Any chance we could improve the visibility of the links in the footer? I wonder if we are breaking any a11y rules by using gray on black... 

Screen Shot 2019-12-02 at 3 47 57 PM

Sidebar is cut off even when testing in a big screen. It doesn't happen in Chrome.

Screen Shot 2019-12-02 at 3 48 08 PM

Sidebar looks weird and logo is stretched in Safari: 

Screen Shot 2019-12-02 at 3 48 19 PM

## General Feedback re: Testing 

Please make sure to test in both Safari and Chrome. Chrome + Safari make up 80% of our visitors. 

Screen Shot 2019-12-02 at 3 56 24 PM
Screen Shot 2019-12-02 at 3 56 42 PM

**Comment by nykka** [comment]
> Also, does GitHub Pages have support for running a rake task before deploying changes? Just wondering if this will work seamlessly when we merge it to `gh-pages`. 

@etagwerker I think we should remove the `static` folder from the `.gitignore' file in order to have it available for deploy.

> So far it looks like gemifying the style guide broke GitHub Pages: https://fastruby.github.io/styleguide/

@etagwerker that's because Sasha changes/branch has been merged to `gh-pages` branch even thought it was not ready for merging.

**Comment by etagwerker** [comment]
@nykka I don't think this is ideal: 

> @etagwerker I think we should remove the static folder from the `.gitignore' file in order to have it available for deploy.

GitHub Pages has a way to automatically generate HTML from Jekyll. I know that we are not using Jekyll for our style guide, but in the future it would be interesting to explore a solution that is GitHub-based and it doesn't require us to constantly update the generated HTML in the Git repo. /cc @bronzdoc

**Review by etagwerker — APPROVED** [review]
@nykka Looks good, thanks! 💯

**Pull request merged**
